# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

screen=STEADFAST <profile> [EFFECTS] [WATER] [ATMOSPHERE_CLOUDS] [LIGHTING] [DEVELOPMENT]
screen.EFFECTS=GODRAYS NIGHT_DESATURATION_EFFECT SATURATED_TONEMAP
screen.ATMOSPHERE_CLOUDS=DAY_ATMOSPHERE NIGHT_ATMOSPHERE HARDER_HORIZON_DAY HARDER_HORIZON_NIGHT BORDER_FOG ATMOSPHERE_FOG_STRENGTH_NOON PLANAR_CLOUD_LAYERS
screen.WATER=FANCY_TRANSLUCENTS VANILLA_ISH_WATER SCREENSPACE_REFLECTIONS SCREENSPACE_REFRACTION WATER_PARALLAX WATER_PARALLAX_DISTANCE WATER_AA NUM_CRESTS NUM_RIPPLES NUM_CAUSTICS WATER_SURFACE DARKEN_UNDERWATER WATER_CAUSTICS WATER_CHARACTER
screen.LIGHTING=DAY_SKY_LIGHTING NIGHT_SKY_LIGHTING ORANGER_BLOCKLIGHT HELD_BLOCK_LIGHTING SHADOW_SOFTNESS SOFTER_SHADOWS SHADOW_DISTORT_FACTOR shadowMapResolution shadowDistance REAL_TIME_SHADOWS DIRECTIONAL_SKYLIGHT_SHADING
screen.DEVELOPMENT=DEBUG FREEZE_ANIMATION_TIMER PREFER_FDM_GRADIENT *

sliders=shadowDistance
