# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Stronger wind during rain (100% to 150% strength)
uniform.float.windStrengthHalf=0.09 * ((1.0 + 0.5 * rainStrength) / 2.0)

# Wind chaos factor to add into windTheta to make it "whip around"
variable.vec4.windChaos=vec4( \
	sin(0.14 * frameTimeCounter * 3.141), \
	sin(0.15 * frameTimeCounter * 3.141), \
	sin(0.16 * frameTimeCounter * 3.141), \
	sin(0.17 * frameTimeCounter * 3.141)  \
)

# XYZ = wind direction theta, W = wind magnitude theta
uniform.vec4.windTheta = vec4( \
	3.141 * ((frameTimeCounter * 1.1) + (1.6 * (windChaos.x + windChaos.y))), \
	3.141 * ((frameTimeCounter * 1.8) + (1.0 * (windChaos.x + windChaos.w))), \
	3.141 * ((frameTimeCounter * 1.2) + (1.6 * (windChaos.z + windChaos.w))), \
	3.141 * ((frameTimeCounter * 0.7)                                      )  \
)
