# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# The ambient term of this atmospheric model is a blue color with an intensity
# varying based on the sun elevation (sunY, the y-component of the unit vector
# of the sun direction).
#
# Though this term is not physically-based in the slightest, it acts as a
# compelling approximation for multi-scattering, and at the same time mitigates
# the artifacts of our approximation of Mie and Rayleigh single-scattering.
#
# It has a similar role as the ambient term in the Phong lighting model, that
# is, a constant color contribution that approximates a much more complex
# underlying phenomenon, in the case of Phong, that of global illumination or
# indirect lighting.
#
# Pleasing blue color
variable.vec3.ambientColor=vec3(0.13, 0.33, 1.0)

# First S-curve from blue hour to morning, and from evening to blue hour
# I call it sunrise, but it applies just the same to sunset.
variable.float.sunriseAA=0.2 / (1.0 + exp(-30.0 * (worldSunVector.y + 0.05)))

# Second S-curve from morning, through noon, to the evening.
variable.float.daytimeAA=0.2 / (1.0 + exp(-15.0 * (worldSunVector.y - 0.45)))

# The ambient contribution is the product of the constant color and varying
# intensities.
variable.vec3.atmosphericAmbient=vec3( \
	(sunriseAA + daytimeAA) * ambientColor.r, \
	(sunriseAA + daytimeAA) * ambientColor.g, \
	(sunriseAA + daytimeAA) * ambientColor.b)

# Rayleigh scatteing coefficient as used by Bruneton, given wavelengths
# of 680 nm (red), 550 nm (green), and 440 nm (blue)
#
# Expressed with the unit (10^-6)*(m^-1), aka "per 1000km"
variable.vec3.RAYLEIGH_SCATTER_COEFFICIENTS=vec3(5.8, 13.5, 33.1)

# Mie scattering coefficient. Bruneton uses 20.0, but because we take a
# shortcut of using the same scale height for Rayleigh and Mie scattering in
# the scattering integral, this tweak is part of what prevents Mie scattering
# from becoming excessively dominant.
#
# Expressed with the unit (10^-6)*(m^-1), aka "per 1000km"
variable.float.MIE_SCATTER_COEFFICIENT=5.0

# The radius of the planet (Earth) used by Bruneton.
#
# Technically, this is very close to the radius near the poles, which is
# 6357 km, but this is not far off of the equatorial radius of 6378 km.
# 
# https://en.wikipedia.org/wiki/Earth_radius
variable.float.PLANET_RADIUS_KM=6360.0

# These values are somewhat arbitrary though are inspired by Earth-like values.
# I mostly selected them by tweaking them incrementally over time. They are not
# set in stone or derived from underlying physics.
#
# For context, Bruneton uses an atmosphere 60km thick.
#
# Typically, Nishita scattering uses separate scale heights for Rayleigh and
# Mie scattering. Using a single scale height allows merging together some
# calculations at the cost of some appearance changes.
#
# Typically, Mie and Rayleigh scattering use quite different scale heights
# (8 km for Rayleigh, 1.2 km for Mie). However, in our atmosphere the primary
# contribution in the scattering integral is from Rayleigh scattering, so
# we can skip some calculations by using the same height for Mie scattering.
variable.float.ATMOSPHERE_THICKNESS_KM=100.0
variable.float.SCALE_HEIGHT_KM=25.0

# We measure lengths in a space where the atmosphere radius is 1.0, that is,
# the atmosphere is a unit sphere.
#
# This scaling is worth it, because it does not require additional operations
# elsewhere outside of changing the constants in use. It is therefore a free
# reduction in computation because computing intersections against a unit
# sphere involves simpler calculations.
variable.float.ATMOSPHERE_RADIUS_KM=PLANET_RADIUS_KM + ATMOSPHERE_THICKNESS_KM
variable.float.KM_TO_UNIT=1.0 / ATMOSPHERE_RADIUS_KM
variable.float.PLANET_RADIUS_UNIT=KM_TO_UNIT * (PLANET_RADIUS_KM)
variable.float.SCALE_HEIGHT_UNIT=KM_TO_UNIT * (SCALE_HEIGHT_KM)

# Scattering coefficients scaled to work with a unit sphere when calculating
# optical depth.
#
# The original coefficients are given with the units (10^-6)*(m^-1), aka
# "per 1000km". Because the lengths used for optical depth calculations are
# in the space where the atmosphere is a unit sphere, we can avoid extra
# computation by converting the units of these coefficients.
#
# We can multiply by (1 megameter / 1000 km) such that the coefficients are
# "per km", then multiply by the atmosphere radius divided by the unit radius.
# Numerically, the unit radius is 1, hence we get the following:
variable.float.COEFFICIENT_TO_UNIT=ATMOSPHERE_RADIUS_KM * (1.0 / 1000.0)
variable.vec3.RAYLEIGH_UNIT=vec3( \
	COEFFICIENT_TO_UNIT * RAYLEIGH_SCATTER_COEFFICIENTS.r, \
	COEFFICIENT_TO_UNIT * RAYLEIGH_SCATTER_COEFFICIENTS.g, \
	COEFFICIENT_TO_UNIT * RAYLEIGH_SCATTER_COEFFICIENTS.b)
variable.float.MIE_UNIT=COEFFICIENT_TO_UNIT * MIE_SCATTER_COEFFICIENT

# In normal atmospheric scattering, we would set the eye height at the real
# height compared to sea level, which would be close to zero in our case.
#
# However, because our near-surface atmosphere approximation wraps the horizon
# around the bottom to mimic the sky of vanilla Minecraft, and because
# Minecraft's height range is very small even between the ocean and the top of
# mountains, it is better to use values from some distance off the ground.
#
# 5 km is not a fixed value, but worked well in my testing. Otherwise, the
# unit height scaling is the same as above.
variable.float.EYE_HEIGHT_KM=5.0
variable.float.EYE_HEIGHT_UNIT=KM_TO_UNIT * (PLANET_RADIUS_KM + EYE_HEIGHT_KM)
