# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# During daytime, add in an ambient blue color (or gray during rain) on top
# of the atmospheric scattering to mitiate most of the artifacts of our
# approximations.
variable.float.atmosphericAmbientLuminance=\
	0.2126 * atmosphericAmbient.r + \
	0.7152 * atmosphericAmbient.g + \
	0.0722 * atmosphericAmbient.b
uniform.vec3.ambientSkyColor=vec3( \
	mix(atmosphericAmbient.r, atmosphericAmbientLuminance, 0.8 * rainStrength),\
	mix(atmosphericAmbient.g, atmosphericAmbientLuminance, 0.8 * rainStrength),\
	mix(atmosphericAmbient.b, atmosphericAmbientLuminance, 0.8 * rainStrength))

# Exposure boost near sunrise because we do not use autoexposure, but
# the atmosphere is much darker near sunrise and normally autoexposure
# would have brightened it for us.
variable.float.exposureDay=25.0 + 35.0 * exp(-15.0 * max(0.0, worldSunVector.y))
variable.float.exposureNight=mix(0.33, 2.4, nightVision)

# The mie strength primarily controls the presence and size of the bright
# spot around the sun and moon. We model the sky during rain as full cloud
# coverage, so it would be unrealistic for mie scattering to be prominent,
# because the clouds would scatter the light mostly uniformly anyhow.
#
# This calculation includes the scattering coefficient and exposure as it
# is multiplied with the transmittance integral and mie phase function to
# calculate the sky color from mie scattering.
variable.float.mieStrength=MIE_SCATTER_COEFFICIENT * (1.0 - rainStrength)
uniform.float.mieStrengthSun=exposureDay * mieStrength * 0.66
uniform.float.mieStrengthMoon=exposureNight * mieStrength

uniform.vec3.rayleighStrengthSun=vec3( \
	exposureDay * RAYLEIGH_SCATTER_COEFFICIENTS.r, \
	exposureDay * RAYLEIGH_SCATTER_COEFFICIENTS.g, \
	exposureDay * RAYLEIGH_SCATTER_COEFFICIENTS.b)
uniform.vec3.rayleighStrengthMoon=vec3( \
	exposureNight * RAYLEIGH_SCATTER_COEFFICIENTS.r, \
	exposureNight * RAYLEIGH_SCATTER_COEFFICIENTS.g, \
	exposureNight * RAYLEIGH_SCATTER_COEFFICIENTS.b)

# Sky color overrides
#
# These override colors allow us to change the color of the sky without changing
# its luminance. These colors must have a luminance of 1, which allows avoiding
# changing the luminance when replacing the color. The alpha value determines
# the blending factor between the real color and the override color, with 1
# meaning no real color (full blending).
#
# We use this during rain, where we recolor to gray, and at night, where we
# recolor to a blue-gray color as a form of stylization.
#
# By definition of the luminance intensities (0.2126, 0.7152, 0.0722),
# (1.0, 1.0, 1.0) has a luminance of 1 already as the sum of the luminance
# intensities is 1.
uniform.vec4.daySkyOverride=vec4(1.0, 1.0, 1.0, rainStrength)
uniform.vec4.daySkyOverridePremultiplied=vec4( \
	daySkyOverride.r * daySkyOverride.a, \
	daySkyOverride.g * daySkyOverride.a, \
	daySkyOverride.b * daySkyOverride.a, \
	1.0 - daySkyOverride.a)

# These are the same colors originally used for the horizon and zenith on the
# semi-natural profile. I decided to leave them as is as they are both pleasing
# and explicitly mix between them to leave the door open for possible tweaking.
variable.float.nightSkyMix=0.66
variable.vec3.nightSkyGrayBase=vec3(0.25, 0.575, 1.0)
variable.vec3.nightSkyBlueBase=vec3(0.07, 0.45, 1.0)

# We must normalize the luminance of the overridden color, that is, ensure that
# the luminance is 1.
variable.float.nightSkyGrayLuminance=\
	0.2126 * nightSkyGrayBase.r + \
	0.7152 * nightSkyGrayBase.g + \
	0.0722 * nightSkyGrayBase.b
variable.float.nightSkyBlueLuminance=\
	0.2126 * nightSkyBlueBase.r + \
	0.7152 * nightSkyBlueBase.g + \
	0.0722 * nightSkyBlueBase.b
variable.vec3.nightSkyGray=vec3( \
	nightSkyGrayBase.r / nightSkyGrayLuminance, \
	nightSkyGrayBase.g / nightSkyGrayLuminance, \
	nightSkyGrayBase.b / nightSkyGrayLuminance)
variable.vec3.nightSkyBlue=vec3( \
	nightSkyBlueBase.r / nightSkyGrayLuminance, \
	nightSkyBlueBase.g / nightSkyGrayLuminance, \
	nightSkyBlueBase.b / nightSkyGrayLuminance)
variable.vec4.nightSkyOverride=vec4( \
	mix(mix(nightSkyGray.r, nightSkyBlue.r, nightSkyMix), 1.0, rainStrength), \
	mix(mix(nightSkyGray.g, nightSkyBlue.g, nightSkyMix), 1.0, rainStrength), \
	mix(mix(nightSkyGray.b, nightSkyBlue.b, nightSkyMix), 1.0, rainStrength), \
	1.0)
uniform.vec4.nightSkyOverridePremultiplied=vec4( \
	nightSkyOverride.r * nightSkyOverride.a, \
	nightSkyOverride.g * nightSkyOverride.a, \
	nightSkyOverride.b * nightSkyOverride.a, \
	1.0 - nightSkyOverride.a)
