# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Direct light source vectors transformed to different spaces.

# Normalized light source vectors - the position vectors are of length 100,
# so divide by 100 since we do not have normalize() here.
variable.vec3.sunVector=vec3( \
	sunPosition.x / 100.0, \
	sunPosition.y / 100.0, \
	sunPosition.z / 100.0)
uniform.vec3.lightVector=vec3( \
	shadowLightPosition.x / 100.0, \
	shadowLightPosition.y / 100.0, \
	shadowLightPosition.z / 100.0)

# Same, but in world space.
uniform.vec3.worldSunVector = vec3( \
	gbufferModelViewInverse.x.0 * sunVector.x \
		+ gbufferModelViewInverse.y.0 * sunVector.y \
		+ gbufferModelViewInverse.z.0 * sunVector.z, \
	gbufferModelViewInverse.x.1 * sunVector.x \
		+ gbufferModelViewInverse.y.1 * sunVector.y \
		+ gbufferModelViewInverse.z.1 * sunVector.z, \
	gbufferModelViewInverse.x.2 * sunVector.x \
		+ gbufferModelViewInverse.y.2 * sunVector.y \
		+ gbufferModelViewInverse.z.2 * sunVector.z)

uniform.vec3.worldLightVector = vec3( \
	gbufferModelViewInverse.x.0 * lightVector.x \
		+ gbufferModelViewInverse.y.0 * lightVector.y \
		+ gbufferModelViewInverse.z.0 * lightVector.z, \
	gbufferModelViewInverse.x.1 * lightVector.x \
		+ gbufferModelViewInverse.y.1 * lightVector.y \
		+ gbufferModelViewInverse.z.1 * lightVector.z, \
	gbufferModelViewInverse.x.2 * lightVector.x \
		+ gbufferModelViewInverse.y.2 * lightVector.y \
		+ gbufferModelViewInverse.z.2 * lightVector.z)

# Screen-space light position, pre-transformed here to avoid needing to do this
# in a vertex shader of a full-screen pass.
#
# The custom uniforms expression language does not support matrix/vector math
# natively, so we must manually write out the matrix multiplication in scalar
# operations.
#
# Recall that matrix-vector multiplication involves taking the dot product of
# each matrix row with the vector we are multiplying with. Since the light
# direction is a vector and not a position, in homogenous coordinates W would be
# 0.0, so we can simply take the dot product of the XYZ components of each row
# with the 3D light vector.
#
# Equivalent GLSL operation:
#
# vec4 clipLightVector = gbufferProjection * vec4(lightVector, 0.0)
#
# TODO: In the OptiFine documentation, it says that the address mode is 
#       Matrix.Row.Column, but the Iris implementation uses Matrix.Column.Row.
#
# Code reference:
#
# https://github.com/IrisShaders/Iris
# Commit: f067d7c315058518021aff3ae577cc3601d0dd77
# /src/main/java/net/irisshaders/iris/parsing/IrisFunctions.java#L1054
#
# I wonder if OptiFine behavior is the same?
# It's not really easy to check because OptiFine is not open-source :/
variable.vec4.clipLightVector = vec4( \
	gbufferProjection.x.0 * lightVector.x \
		+ gbufferProjection.y.0 * lightVector.y \
		+ gbufferProjection.z.0 * lightVector.z, \
	gbufferProjection.x.1 * lightVector.x \
		+ gbufferProjection.y.1 * lightVector.y \
		+ gbufferProjection.z.1 * lightVector.z, \
	gbufferProjection.x.2 * lightVector.x \
		+ gbufferProjection.y.2 * lightVector.y \
		+ gbufferProjection.z.2 * lightVector.z, \
	gbufferProjection.x.3 * lightVector.x \
		+ gbufferProjection.y.3 * lightVector.y \
		+ gbufferProjection.z.3 * lightVector.z)

# TODO: For screen-space shadows where we use this even when not looking at
# the sun, we will need to constrain W when it gets too close to zero for
# the X and Y components, and have a W=0.0 check for the Z component.
variable.vec3.ndcLightVector=vec3( \
	clipLightVector.x / clipLightVector.w, \
	clipLightVector.y / clipLightVector.w, \
	clipLightVector.z / clipLightVector.w)

# The light vector in the screen space, for more information see:
# https://shaderlabs.org/wiki/Coordinate_Spaces
#
# Each coordinate has a nominal range of 0.0 to 1.0, but the actual
# coordinates here can exist outside of that range because the light
# is not actually within the screen, but rather is infinitely far
# away being a purely directional light source.
#
# The X and Y values are the positions on the screen, the Z component
# is the nonlinear depth value, and the W component is an indicator of
# whether the light is in front of the camera (1.0), or behind it (-1.0).
uniform.vec4.screenLightVector=vec4( \
	ndcLightVector.x * 0.5 + 0.5, \
	ndcLightVector.y * 0.5 + 0.5, \
	ndcLightVector.z * 0.5 + 0.5, \
	if(clipLightVector.w > 0.0, 1.0, -1.0))

# The light vector in the window texel/pixel space.

# The X and Y components are in units of pixels, and the Z and W components
# are identical to screenLightVector.
uniform.vec4.windowLightVector=vec4( \
	screenLightVector.x * viewWidth, \
	screenLightVector.y * viewHeight, \
	screenLightVector.z, \
	screenLightVector.w)

# These are the view-space vectors that represent a one-pixel offset along the X
# and Y axis in screen-space, respectively.
uniform.vec3.viewOffsetPixelX=vec3( \
	gbufferProjectionInverse.x.0 * (2.0 / viewWidth), \
	gbufferProjectionInverse.y.0 * (2.0 / viewWidth), \
	gbufferProjectionInverse.z.0 * (2.0 / viewWidth))
uniform.vec3.viewOffsetPixelY=vec3( \
	gbufferProjectionInverse.x.1 * (2.0 / viewHeight), \
	gbufferProjectionInverse.y.1 * (2.0 / viewHeight), \
	gbufferProjectionInverse.z.1 * (2.0 / viewHeight))
